import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "@uploadthing/react/styles.css";

import TopNav from "./_components/topnav";

export const metadata: Metadata = {
  title: "Gallery Web App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex min-h-screen flex-col gap-4 bg-gradient-to-b from-[#2e026d] to-[#15162c] p-4 text-white">
          <TopNav />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
